import { db } from "../config/db.js";
import { events } from "../db/schema/index.js";
import { eq, and } from "drizzle-orm";
import cron from "node-cron";

export class SundayService {
  static async ensureSundayServiceExists() {
    try {
      const today = new Date();

      
      // Only proceed if today is Sunday (0 = Sunday)
      if (today.getDay() !== 0) {
        console.log(`ℹ️  Not Sunday (${today.getDay()}), skipping Sunday service check`);
        return { created: false, reason: 'Not Sunday' };
      }

      const todayStr = today.toISOString().split('T')[0];

      
      // Check if Sunday service already exists for today
      const existingService = await db
        .select()
        .from(events)
        .where(and(
          eq(events.date, todayStr),
          eq(events.eventType, 'sunday_service')
        ));

      // If no service exists, create it
      if (existingService.length === 0) {
        const [newEvent] = await db
          .insert(events)
          .values({
            name: `Sunday Service - ${today.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}`,
            eventType: 'sunday_service',
            date: todayStr,
            autoGenerated: true,
            createdBy: null // System user
          })
          .returning();

        console.log(`✅ Auto-created Sunday service for ${todayStr}`);
        return { created: true, event: newEvent };
      }

      console.log(`ℹ️  Sunday service already exists for ${todayStr}`);
      return { created: false, reason: 'Already exists' };
    } catch (error) {
      console.error('❌ Failed to ensure Sunday service:', error);
      return { created: false, reason: 'Error', error };
    }
  }

  static startDailyCheck() {
    // Run every day at 6:00 AM
    cron.schedule('0 6 * * *', async () => {
      console.log('🕒 Running daily Sunday service check...');
      await this.ensureSundayServiceExists();
    });
    
    console.log('✅ Sunday service daily check scheduled (6:00 AM daily)');
  }

  // Manual trigger for testing or emergency use
  static async manualTrigger() {
    console.log('🔄 Manually triggering Sunday service check...');
    return await this.ensureSundayServiceExists();
  }
}